### ISSUE TITLE
Android buildToolsVersion

### ISSUE THREAD

**Issue by masartbenji** [codenameone/CameraKitCodenameOne#10]
Hello,

I'm currently switching the api level of my codenameone app to 30 but when i tried to build my app on codename one server I have an error due to the build tools version of your library. If I check your "codenameone_library_required.properties", you set the version to 28 and it provoke a conflict between the buildtoolsversion I set to  30 in codenameone_settings.properties and your buildtoolsversions

Best regards

**Comment by shannah** [comment]
https://github.com/codenameone/CameraKitCodenameOne/commit/ef5be61c0138c64fbfd773f5e0f560f15ea01263
