### ISSUE TITLE
onVideo event not firing

### ISSUE THREAD

**Issue by thomasmcneill** [codenameone/CameraKitCodenameOne#2]
The onVideo event does not fire on the demo application.   CameraKit-Android has the same issue and has been mark as closed because it will be solved in V1.0.0.  Issue # 229.  https://github.com/CameraKit/camerakit-android/issues/229

See the comment from UnknownGod on Nov 22, 2017 for a fix.

**Comment by shannah** [comment]
The latest version no longer uses the Android CameraKit library.  Update through CodenameOne settings - should resolve the issue.
