### ISSUE TITLE
WHAT IS THE CameraKitDemo?

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CameraKitCodenameOne#4]
inside this project there is  a CameraKit Demo. But in the wiki documentation there is other. Could you tell me what the true Demo project?

**Comment by shannah** [comment]
The one in this repo is the most current.  I have updated the README to link to that one.
https://github.com/codenameone/CameraKitCodenameOne/commit/1f2c7ed015b3a4994406dbe629ca320b613854e9
